name: Build and Test Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    # runs-on: [ node-20 ]

    services:
      mongo:
        image: mongodb/mongodb-community-server:latest
        ports:
          - 27017:27017

      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - name: Installing node
        shell: sh
        run: |
          apt update && apt install curl -y
          curl -fsSL https://deb.nodesource.com/setup_20.x | sh -
          apt install nodejs -y
          npm install -g pnpm

      - name: Installing Git
        shell: sh
        run: |
          apt install git -y

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        shell: sh
        with:
          driver: docker-container

      - name: Build and run Docker Compose
        run: |
          docker compose -f build.docker-compose.yml up --build --exit-code-from app --remove-orphans
          docker compose -f build.docker-compose.yml down --volumes --remove-orphans

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./dist
