name: Build and Test Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-22.04-docker

    services:
      mongo:
        image: mongodb/mongodb-community-server:latest
        ports:
          - 27017:27017

      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - name: Installing node
        shell: sh
        run: |
          apt update && apt install curl -y
          curl -fsSL https://deb.nodesource.com/setup_20.x | sh -
          apt install nodejs -y
          npm install -g pnpm

      - name: Installing Git
        shell: sh
        run: |
          apt install git -y

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          cp .env.example-build .env

      - name: Build astro project
        run: |
          pnpm install --frozen-lockfile
          pnpm run build-silent
          tar -czvf sepomex.tar.gz ./dist

      - name: Wait for Docker daemon
        shell: sh
        run: |
          timeout=300  # Set a timeout value in seconds
          until docker info; do
            echo "Waiting for Docker daemon to start..."
            sleep 5
            timeout=$((timeout-5))
            if [ $timeout -le 0 ]; then
              echo "Timeout waiting for Docker daemon to start."
              exit 1
            fi
          done

      - name: Build and Docker container
        shell: sh
        run: |
          docker build -f deploy.Dockerfile -t git.nitrostudio.com.mx/marco/sepomex:$GITHUB_REF_NAME .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: git.nitrostudio.com.mx
          username: ${{ secrets.FORGEJO_USERNAME }}
          password: ${{ secrets.FORGEJO_PASSWORD }}

      - name: Push Docker image
        shell: sh
        run: |
          docker push git.nitrostudio.com.mx/marco/sepomex:$GITHUB_REF_NAME
          docker logout

      #      - name: Create Release
      #        id: create_release
      #        uses: actions/forgejo-release@v2
      #        env:
      #          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #        with:
      #          tag_name: ${{ github.ref_name }}
      #          release_name: Release ${{ github.ref_name }}
      #          draft: false
      #          prerelease: false

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sepomex
          retention-days: 30
          path: ./sepomex.tar.gz
