name: Build and Test Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04-docker

    services:
      mongo:
        image: mongodb/mongodb-community-server:latest
        ports:
          - 27017:27017

      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - name: Installing node
        shell: sh
        run: |
          apt update && apt install curl -y
          curl -fsSL https://deb.nodesource.com/setup_20.x | sh -
          apt install nodejs -y
          npm install -g pnpm

      - name: Installing Git
        shell: sh
        run: |
          apt install git -y

      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Wait for Docker daemon
#        shell: sh
#        run: |
#          timeout=300  # Set a timeout value in seconds
#          until docker info; do
#            echo "Waiting for Docker daemon to start..."
#            sleep 5
#            timeout=$((timeout-5))
#            if [ $timeout -le 0 ]; then
#              echo "Timeout waiting for Docker daemon to start."
#              exit 1
#            fi
#          done

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#        shell: sh
#        with:
#          driver: docker-container
#        run:

#      - name: Build and run Docker Compose
#        run: |
#          docker compose -f build.docker-compose.yml up --build --exit-code-from app --remove-orphans
#          docker compose -f build.docker-compose.yml down --volumes --remove-orphans

      - name: Create .env file
        run: |
          cp .env.example-build .env

      - name: Build astro project
        run: |
          pnpm install --frozen-lockfile
          pnpm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist
