name: Build and Test Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: [ node-20 ]

    services:
      mongo:
        image: mongodb/mongodb-community-server:latest
        ports:
          - 27017:27017

      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - name: Set up dependencies
        shell: sh
        run: apk add --no-cache git

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run Docker Compose
        run: |
          docker compose -f build.docker-compose.yml up --build --exit-code-from app --remove-orphans
          docker compose -f build.docker-compose.yml down --volumes --remove-orphans

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist
